language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - flake8 .
  - coverage run --source=crashclouseau -m unittest discover tests/ --verbose
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache: pip
